# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 08:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PenguinUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('camera_key', models.CharField(default='', max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PenguinCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, null=True)),
                ('civil_twilight', models.DateTimeField(blank=True, null=True)),
                ('sub_fifteen', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='-15-0')),
                ('zero_to_fifteen', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='0-15')),
                ('fifteen_to_thirty', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='15-30')),
                ('thirty_to_fourty_five', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='30-45')),
                ('fourty_five_to_sixty', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='45-60')),
                ('sixty_to_seventy_five', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='60-75')),
                ('seventy_five_to_ninety', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='75-90')),
                ('ninety_to_one_oh_five', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='90-105')),
                ('one_oh_five_to_one_twenty', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='105-120')),
                ('total_penguins', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='total penguins')),
                ('outlier', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='outlying times')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PenguinObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='count')),
                ('comments', models.TextField(blank=True, null=True)),
                ('wind_direction', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'N'), (2, 'NNW'), (3, 'NW'), (4, 'WNW'), (5, 'W'), (6, 'WSW'), (7, 'SW'), (8, 'SSW'), (9, 'S'), (10, 'SSE'), (11, 'SE'), (12, 'ESE'), (13, 'E'), (14, 'ENE'), (15, 'NE'), (16, 'NNE')], null=True, verbose_name='Wind direction')),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Wind speed (km/h)')),
                ('wave_direction', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'N'), (2, 'NNW'), (3, 'NW'), (4, 'WNW'), (5, 'W'), (6, 'WSW'), (7, 'SW'), (8, 'SSW'), (9, 'S'), (10, 'SSE'), (11, 'SE'), (12, 'ESE'), (13, 'E'), (14, 'ENE'), (15, 'NE'), (16, 'NNE')], null=True, verbose_name='Wave direction')),
                ('wave_height', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Wave height (m)')),
                ('wave_period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Wave period (s)')),
                ('moon_phase', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Full'), (2, 'First quarter'), (3, 'Half'), (4, 'Third quarter'), (5, 'New')], null=True, verbose_name='Moon phase')),
                ('raining', models.BooleanField(default=False, help_text='Was it raining at the time of the observation?', verbose_name='Raining?')),
                ('position', models.FloatField(default=0, null=True, verbose_name='Position in video')),
                ('validated', models.BooleanField(default=True, verbose_name='Confirmed')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.Camera')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PenguinVideoObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateField(help_text='The date of the recording.', verbose_name='Date')),
                ('file', models.FileField(upload_to='videos/')),
                ('start_time', models.TimeField(help_text='The start time of the recording.', verbose_name='Start time')),
                ('end_time', models.TimeField(help_text='The end time of the recording (usually 1h after start).', verbose_name='End time')),
                ('views', models.IntegerField(default=0)),
                ('mark_complete', models.BooleanField(default=False, help_text='Has this been viewed in its entirety by a reviewer')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.Camera')),
                ('completed_by', models.ManyToManyField(related_name='videos_seen', to=settings.AUTH_USER_MODEL, verbose_name='Users who have seen this video')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='penguinvideoobservation',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.Video'),
        ),
        migrations.AddField(
            model_name='penguinobservation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.Site'),
        ),
        migrations.AddField(
            model_name='penguinobservation',
            name='video',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.Video', verbose_name='Video filename'),
        ),
        migrations.AddField(
            model_name='penguincount',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.Site'),
        ),
        migrations.AddField(
            model_name='camera',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.Site'),
        ),
    ]
