# Generated by Django 4.2.20 on 2025-04-22 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='videos_seen', to=settings.AUTH_USER_MODEL, verbose_name='Users who have seen this video'),
        ),
    ]
