# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-26 01:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penguinvideoobservation',
            name='video',
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.RemoveField(
            model_name='camera',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='penguinobservation',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='penguinobservation',
            name='moon_phase',
        ),
        migrations.RemoveField(
            model_name='penguinobservation',
            name='site',
        ),
        migrations.RemoveField(
            model_name='penguinobservation',
            name='wave_direction',
        ),
        migrations.RemoveField(
            model_name='penguinobservation',
            name='wave_height',
        ),
        migrations.RemoveField(
            model_name='penguinobservation',
            name='wave_period',
        ),
        migrations.RemoveField(
            model_name='penguinobservation',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='penguinobservation',
            name='wind_speed',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.AddField(
            model_name='camera',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='penguinobservation',
            name='date',
            field=models.DateTimeField(help_text='The date on which the observation is noted'),
        ),
        migrations.AlterField(
            model_name='penguinobservation',
            name='position',
            field=models.FloatField(default=0, help_text='Position in video (seconds from start)', null=True, verbose_name='Position (s)'),
        ),
        migrations.AlterField(
            model_name='penguinobservation',
            name='raining',
            field=models.BooleanField(default=False, help_text='Was it raining at the time of the observation?'),
        ),
        migrations.AlterField(
            model_name='penguinobservation',
            name='seen',
            field=models.PositiveSmallIntegerField(help_text='The count of penguins seen in this observation.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='penguinobservation',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='observations.Video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(help_text='The date of the recording.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='end_time',
            field=models.TimeField(help_text='The end time of the recording (usually 1h after start).'),
        ),
        migrations.AlterField(
            model_name='video',
            name='mark_complete',
            field=models.BooleanField(default=False, help_text='Has this been viewed in its entirety by a reviewer?'),
        ),
        migrations.AlterField(
            model_name='video',
            name='start_time',
            field=models.TimeField(help_text='The start time of the recording.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PenguinVideoObservation',
        ),
    ]
