# Generated by Django 4.2.20 on 2025-04-22 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0002_alter_video_completed_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="penguinobservation",
            old_name="seen",
            new_name="count",
        ),
    ]
