# Generated by Django 4.2.20 on 2025-04-22 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0003_rename_video_seen_counted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="file",
            new_name="uploaded_file",
        ),
    ]
