# Generated by Django 4.2.20 on 2025-04-22 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_rename_video_file_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penguinobservation',
            name='date',
        ),
        migrations.AlterField(
            model_name='penguinobservation',
            name='count',
            field=models.PositiveSmallIntegerField(help_text='The count of penguins counted in this observation.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
