apiVersion: batch/v1
kind: CronJob
metadata:
  name: penguins-import-cronjob
spec:
  # AWST: 07:05 every day.
  schedule: '5 23 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: penguins-import-cronjob
              args: ['manage.py', 'video_import']
              envFrom:
                - secretRef:
                    name: penguins-env-uat
