apiVersion: batch/v1
kind: CronJob
metadata:
  name: penguins-import-cronjob
spec:
  # 5 minutes past the hour, every hour.
  schedule: '5 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: penguins-import-cronjob
              args: ['manage.py', 'video_import']
              envFrom:
                - secretRef:
                    name: penguins-env-prod
