apiVersion: batch/v1
kind: CronJob
metadata:
  name: penguins-import-cronjob
  labels:
    app: penguins-import-cronjob
spec:
  # AWST: 07:05 every day.
  schedule: '5 23 * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      activeDeadlineSeconds: 600
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: penguins-import-cronjob
              image: ghcr.io/dbca-wa/penguins
              command: ['python']
              args: ['--version']
              env:
                - name: TZ
                  value: 'Australia/Perth'
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                privileged: false
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
              volumeMounts:
                - mountPath: /tmp
                  name: tmpfs-ram
          volumes:
            - name: tmpfs-ram
              emptyDir:
                medium: 'Memory'
          automountServiceAccountToken: false
          tolerations:
            - key: arch
              operator: Equal
              value: arm64
              effect: NoSchedule
